"""Keywords for internship and role filtering."""

INTERN_KEYWORDS = [
    "intern",
    "internship",
    "trainee",
    "industrial training",
]

ROLE_KEYWORDS = [
    "data analyst",
    "data scientist",
    "machine learning",
    "big data",
    "business intelligence",
    "data engineer",
    "ai engineer",
    "artificial intelligence",
    "data architect",
    "business analytics",
    "back-end",
    "backend",
    "software develop",
    "software engineer",
    "database admin",
    "cloud engineer",
    "cloud computing",
    "devops",
    "deep learning",
    "nlp",
    "computer vision",
    "cyber security",
    "cybersecurity",
    "information security",
    "secure software",
    "network security",
    "security operations",
    "soc",
    "digital forensics",
    "vulnerability assessment",
    "penetration testing",
    "incident handling",
    "incident response",
    "secure system",
    "data intelligence",
    "platform security",
    "cloud security",
    "security pre-sales",
    "data privacy",
    "cyber defense",
    "health information security",
    "iot security",
    "industrial security",
    "hardware security",
    "it",
    "system admin",
    "systems admin",
    "system administrator",
    "qa",
    "quality assurance",
    # Additional tech roles
    "frontend",
    "front-end",
    "front end",
    "full stack",
    "fullstack",
    "mobile develop",
    "web develop",
    "web dev",
    "ui developer",
    "ux developer",
    "ui/ux",
    "application develop",
    "app develop",
    "programmer",
    "network engineer",
    "network admin",
    "system engineer",
    "test engineer",
    "automation engineer",
    "software testing",
    "software quality",
    "site reliability",
    "sre",
    "platform engineer",
    "infrastructure engineer",
    "technical support",
    "tech support",
    "application support",
    "help desk",
    "service desk",
    "java develop",
    "python develop",
    "javascript",
    "react",
    "angular",
    "node",
    "sql develop",
    "power bi",
    "tableau",
    "tester",
    "quality engineer",
    "embedded",
    "firmware",
    "solution architect",
    "technical architect",
    "data engineering",
    "software engineering",
    "tech intern",
    "product develop",
    "research & develop",
    "r&d",
    "blockchain",
    "data warehouse",
    "etl",
    "agile",
    "tech lead",
    "technical lead",
    "scrum master",
    "information technology",
    "computer science",
    "computer engineering",
    "software",
    "coding",
    "programming",
    "development intern",
    "technology intern",
    "tech",
    "dba",
    "business analysis",
    "systems analysis",
    "it support specialist",
    "business system consultant",
    "erp support",
    "project management",
    "database administrator",
    "business intelligence engineering",
    "application support engineer",
    "integration specialist",
    "software testing - manual",
    "software testing - automation",
    "requirements engineering",
    "ui/ux engineering",
]
